// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeby2Ydyse3XPnBlTjjxYomTaPHnb99CA',
    appId: '1:838441516202:web:828fc67ee614c2aa8aa4d3',
    messagingSenderId: '838441516202',
    projectId: 'test-6ad12',
    authDomain: 'test-6ad12.firebaseapp.com',
    storageBucket: 'test-6ad12.appspot.com',
    measurementId: 'G-6L9JGGLNGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-uxwZ4xP4C5vWlkyJ2Z5X_zghWx1jHrg',
    appId: '1:838441516202:android:980bdb77e07be87c8aa4d3',
    messagingSenderId: '838441516202',
    projectId: 'test-6ad12',
    storageBucket: 'test-6ad12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4Zg9wtybZJTrwipvs1NzMUDhK6ychXA',
    appId: '1:838441516202:ios:2525dc282197f1448aa4d3',
    messagingSenderId: '838441516202',
    projectId: 'test-6ad12',
    storageBucket: 'test-6ad12.appspot.com',
    iosClientId: '838441516202-l5693pq8trl3vmtr7onc12utpvntm5f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApplication',
  );
}
